arm_position_configuration: Home

RATE_HZ: 900
PARAMETERS_COUNT: 7
task_time_limit_sec: 10  # in seconds 
test_joint: 6
actuator_count: 7

offline_mode: True  
get_static_torque: False
get_dynamic_values: True
