arm_position_configuration: friction_configuration_joint_7
joint_choice: 7
RATE_HZ: 900
PARAMETERS_COUNT: 7
task_time_limit_sec: 10  # in seconds 
test_joint: 6
actuator_count: 7
jnt_ctrl_torque_vec_start: 0.1
initial_torque_increment_rate: 0.05
breakaway_torque_samples: 10
number_of_rate_increments: 5
breakaway_torque_iterations: 50

offline_mode: False  
get_static_torque: False
get_dynamic_values: True

different_velocity_values:
  - 0.1
  - 0.3
  - 0.5
  - 0.9
  - 1.3

joint_velocity_limits:
  - 1.74
  - 1.74
  - 1.74
  - 1.74
  - 2.6
  - 2.6
  - 2.6

motor_torque_constant:
  - 11.0
  - 11.0
  - 11.0
  - 11.0
  - 7.6
  - 7.6
  - 7.6

joint_current_limits:
  - 9.5
  - 9.5
  - 9.5
  - 9.5
  - 5.5
  - 5.5
  - 5.5

home_configuration:
  - 0.0
  - 15.0
  - 180.0
  - 230.0
  - 0.0
  - 55.0
  - 90.0

zero_configuration:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0

friction_configuration_joint_7:
  - 0.0
  - 15.0
  - 180.0
  - 230.0
  - 6.7
  - 46.16
  - 92.0

joint_inertia:
  - 0.5580
  - 0.5580
  - 0.5580
  - 0.5580
  - 0.1389
  - 0.1389
  - 0.1389

friction_estimation_D_gain:
  - 30.0
  - 30.0
  - 30.0
  - 30.0
  - 20.0
  - 20.0
  - 20.0

friction_estimation_P_gain:
  - 70.0
  - 70.0
  - 70.0
  - 70.0
  - 50.0
  - 50.0
  - 50.0

friction_estimation_I_gain:
  - 30.0
  - 30.0
  - 30.0
  - 30.0
  - 20.0
  - 20.0
  - 20.0
